import dotenv from "dotenv";

dotenv.config();

const {
  NODE_ENV,
  PORT,
  DB_CONNECTION_STRING,
  FRONTEND_URL,
  JWKS_URI,
  REFRESH_TOKEN_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
} = process.env;

export const CONFIG = Object.freeze({
  NODE_ENV,
  PORT,
  DB_CONNECTION_STRING,
  FRONTEND_URL,
  JWKS_URI,
  REFRESH_TOKEN_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
});
